apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128M
