apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnsmasq
spec:
  capacity:
    storage: 128M
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: s
  local:
    path: /mnt/dnsmasq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
