apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/pihole
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128M
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
