apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq
  namespace: default
spec:
  accessModes:
  - RWX
  resources:
    requests:
      storage: 128M
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
