apiVersion: v1
kind: PersistentVolume
metadata:
  name: s
spec:
  capacity:
    storage: 128M
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: s
  local:
    path: /mnt/dnsmasq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq
spec:
  storageClassName: s
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128M
