apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.kubernetes.io/storage-provisioner: microk8s.io/hostpath
  name: dnsmasq
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128M
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
