apiVersion: v1
kind: PersistentVolumeClaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128M
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
